-- ============================================================================
-- Migration 183: Eksik şema kolonları (canlı sistem hata düzeltmeleri)
-- ----------------------------------------------------------------------------
-- Kök neden:
--   Canlı sistemde (uzak PG `retailex_demo`) 4 farklı SQL hatası:
--     1) `listInProgressAppointments` → `column rs.color does not exist`
--        (rex_*_services.color kolonu master şemada yok — KOD tarafında
--        `COALESCE(bs.color, rs.color)` → `bs.color` olarak düzeltildi)
--     2) `getCustomerOutstandingInvoices` → `column "currency" does not exist`
--        (beauty.rex_*_*_beauty_sales.currency kolonu master şemada yok idi;
--        master şemaya currency eklendi)
--     3) `getCustomerOutstandingInvoices` → `column "paid_amount" does not exist`
--        (public.rex_*_*_sales.paid_amount kolonu yok idi; master şemaya
--        eklendi; credit_amount zaten vardı)
--     4) `service_staff_commissions` PostgREST 400 — bazı tenant'larda
--        INIT_BEAUTY_FIRM_TABLES çağrılmamış (kısmi kurulum / snapshot);
--        tablo CREATE ile garanti edildi
--
-- Politikalar:
--   * Idempotent: ADD COLUMN IF NOT EXISTS / CREATE TABLE IF NOT EXISTS
--   * Geriye dönük uyumluluk: yeni kolonlar DEFAULT değerli (paid_amount=0,
--     currency='IQD')
--   * DO $$ ... $$ BLOKLARI KULLANILMAMIŞTIR (Tauri Rust parser uyumu)
--   * Çoklu tenant/firm/period uygulaması için apply script'i kullanılır
--
-- Uygulama:
--   node database/scripts/apply-missing-columns-183.mjs --apply
--   (script: tüm RetailEX tenant DB'lerini tarar, NON_RETAILEX_DATABASES
--    + finpos_crm + merkez_db'yi atlar, dry-run destekler)
-- ============================================================================

SET search_path TO public;

-- ============================================================================
-- 1) public.rex_<firmNr>_<periodNr>_sales.paid_amount EKLE
-- ----------------------------------------------------------------------------
-- `credit_amount` master şemada zaten VAR (kalan veresiye bakiyesi).
-- `paid_amount` tahsil edilen tutar (kümülatif) — POS ödeme / cari tahsilat
-- sorgularının beklediği kolon.
--
-- İlişki:
--   paid_amount + credit_amount = net_amount (toplam fatura tutarı yaklaşık)
--   paid_amount=0, credit_amount=net → veresiye (henüz ödenmemiş)
--   paid_amount=net, credit_amount=0 → peşin (tam ödenmiş)
--
-- İdempotent: ADD COLUMN IF NOT EXISTS (Tauir Rust uyumlu, DO $$ yok).
-- ============================================================================
--
-- Örnek tek ALTER (apply script'i her firm/period için ayrı çalıştırır):
--   ALTER TABLE rex_001_01_sales
--     ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(15,2) NOT NULL DEFAULT 0;

-- ============================================================================
-- 2) beauty.rex_<firmNr>_<periodNr>_beauty_sales.currency EKLE
-- ----------------------------------------------------------------------------
-- beauty_sales zaten `paid_amount` / `remaining_amount` / `payment_status`
-- içeriyor (master 4170); `currency` eklenmediği için
-- `COALESCE(currency, 'IQD')` sorguları runtime'da patlıyordu.
-- ============================================================================
--
-- Örnek tek ALTER:
--   ALTER TABLE beauty.rex_001_01_beauty_sales
--     ADD COLUMN IF NOT EXISTS currency VARCHAR(10) NOT NULL DEFAULT 'IQD';

-- ============================================================================
-- 3) beauty.rex_<firmNr>_service_staff_commissions (eksik tenant'lar)
-- ----------------------------------------------------------------------------
-- INIT_BEAUTY_FIRM_TABLES tarafından yaratılması gereken tablo — bazı
-- tenant'larda hiç çağrılmamış (kısmi kurulum, snapshot, erken kurulum).
-- Sonuç: PostgREST 400 + komisyon sorguları sessizce boş döner.
--
-- INIT_BEAUTY_FIRM_TABLES ile bire bir aynı yapı (4098 ile):
--   - service_id → beauty.rex_*_beauty_services(id) ON DELETE CASCADE
--   - staff_id   → beauty.rex_*_beauty_specialists(id) ON DELETE CASCADE
--   - percent NUMERIC(5,2) CHECK 0..100
--   - PRIMARY KEY (service_id, staff_id)
-- ============================================================================
--
-- Örnek tek CREATE (apply script'i her firm için ayrı çalıştırır):
--   CREATE TABLE IF NOT EXISTS beauty.rex_001_service_staff_commissions (
--     service_id UUID NOT NULL REFERENCES beauty.rex_001_beauty_services(id) ON DELETE CASCADE,
--     staff_id   UUID NOT NULL REFERENCES beauty.rex_001_beauty_specialists(id) ON DELETE CASCADE,
--     percent    NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (percent >= 0 AND percent <= 100),
--     is_active  BOOLEAN NOT NULL DEFAULT true,
--     notes      TEXT,
--     created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     PRIMARY KEY (service_id, staff_id)
--   );
--   CREATE INDEX IF NOT EXISTS rex_001_service_staff_commissions_srv_active_idx
--     ON beauty.rex_001_service_staff_commissions (service_id) WHERE is_active = true;

-- ============================================================================
-- 4) rex_*_services.color (Hata 1 — KOD tarafında çözüldü)
-- ----------------------------------------------------------------------------
-- Bu kolon master şemada YOK ve güzellik dışı modüller için anlamlı değil
-- (services tablosu ürün/malzeme kartı). JOIN'deki `rs.color` referansı
-- `beautyService.ts` içinde kaldırıldı → `bs.color` (beauty_services) zaten
-- doğru yere yönlendiriyor. Bu migration kolon EKLEMİYOR (sıfır etki).
-- ============================================================================