apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s

  - name: PostgreSQL
    type: postgres
    access: proxy
    uid: postgres
    url: postgres:5432
    user: postgres
    isDefault: false
    # Köprü Grafana API ile database alanı güncellenir
    editable: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${GRAFANA_POSTGRES_DATABASE:-postgres}
      sslmode: disable
      maxOpenConns: 4
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
